"""configuration file to filters"""
MIN_NAME_LENGTH = 1
MAX_NAME_LENGTH = 100

MIN_ARTICLE_LENGTH = 10
MAX_ARTICLE_LENGTH = 100

MIN_CURRENCY_LENGTH = 1
MAX_CURRENCY_LENGTH = 50

MAX_AVATAR_PATH_LENGTH = 300

MAX_PASSWORD_LENGTH = 250

PASSWORD_PATTERN = r'[A-Za-z0-9@#$%^&+=]{8,' + str(MAX_PASSWORD_LENGTH) + '}'
