"""configuration file to filters"""
MIN_NAME_LENGTH = 3
MAX_NAME_LENGTH = 100

MIN_ARTICLE_LENGTH = 10
MAX_ARTICLE_LENGTH = 100

MIN_CURRENCY_LENGTH = 1
MAX_CURRENCY_LENGTH = 50

MAX_AVATAR_PATH_LENGTH = 300

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 250

MAX_PUBLIC_ID_LENGTH = 100

MAX_CONTENT_LENGTH = 5 * 1000 * 1000  # 5 mb

PASSWORD_PATTERN = r'[A-Za-z0-9@#$%^&+=]{8,' + str(MAX_PASSWORD_LENGTH) + '}'

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

MAX_PAGE_SIZE = 50

ALLOWED_SORTING_FIELDS = {'article', 'name'}
